<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container8OuVKyp\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container8OuVKyp/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container8OuVKyp.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container8OuVKyp\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container8OuVKyp\App_KernelDevDebugContainer([
    'container.build_hash' => '8OuVKyp',
    'container.build_id' => '770b2efc',
    'container.build_time' => 1679043580,
], __DIR__.\DIRECTORY_SEPARATOR.'Container8OuVKyp');
